version: "3.8"

volumes:
    pgdata:

services:
  postgres-compose:
    image: postgres
    environment:
        - POSTGRES_DB=ormify
        - POSTGRES_USER=Elias
        - POSTGRES_PASSWORD=EliasORM
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "eliasprado123@outlook.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge