version: "3.8"
   
services:
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=ormify
            - POSTGRES_USER=Elias
            - POSTGRES_PASSWORD=EliasORM
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata: